name: msys2-mingw

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
    paths-ignore:
      - LICENSE
      - README.md
      - 'docs/**'
      - 'schemas/**'
  pull_request:
    paths-ignore:
      - LICENSE
      - README.md
      - 'docs/**'
      - 'schemas/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: msys2 {0}

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Release]
        c_compiler: [gcc]
        cpp_compiler: [g++]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: UCRT64
        install: git base-devel mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-ninja mingw-w64-ucrt-x86_64-toolchain mingw-w64-ucrt-x86_64-headers-git

    - name: Add MSYS2 to PATH
      run: echo "C:/msys64/usr/bin" >> $GITHUB_PATH
      shell: pwsh

    - name: Cache build dependencies
      uses: actions/cache@v3
      with:
        path: |
          build/_deps
          ~/.vcpkg
          ~/.cache
        key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Configure CMake
      shell: bash -el {0}
      run: >
        cmake -S . -B build -G Ninja 
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}

    - name: Build
      shell: bash -el {0}
      run: cmake --build build --target dynohook --config ${{ matrix.build_type }} --parallel

#    - name: Test
#      shell: bash -el {0}
#      working-directory: build
#      run: ctest --build-config ${{ matrix.build_type }}
